server:
  port: 8081

camunda.bpm:
  client:
    base-url: http://localhost:8080/engine-rest

spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: fd915793-26c2-4b3d-9eeb-2747e00ef897
        credential:
          client-id: 025bcc79-a2b5-49ad-a42f-8a97449b4904
          client-secret: joM8Q~mj23f4c19fYJRdIp5rO7qng6Z~vczlnaHx
        authorization-clients:
          camundaLocalEngine:
            authorization-grant-type: client_credentials
            scopes: api://8aa265c4-d157-467e-8543-ff7c32cebeb8/.default

logging:
  level:
    org.springframework.security: DEBUG
